### ISSUE TITLE
confused about parameters step_size, from_pos, to_pos in DeepGraph.create_edges

### ISSUE THREAD

**Issue by grez72** [deepgraph/deepgraph#10]
I'm following along with this nice tutorial:
https://deepgraph.readthedocs.io/en/latest/tutorials/pairwise_correlations.html

But I'm confused about the role of the parameters step_size, from_pos, to_pos when calling g.create_edges. If from_pos and to_pos are set, is step_size ignored?

step_size is "The number of pairs of nodes to process at each iteration step."
from_pos is "which pair of nodes to start the iteration process"
to_pos is "which pair of nodes to stop the iteration process"

It seems like if the start/stop nodes are specified, then "step_size" must be "to_pos - start_pos"...but maybe I'm misunderstanding these parameters and whether/how they should be used together.

Thanks!

**Comment by dominiktraxl** [comment]
Let's say you have a set of n=10 nodes, then there are n*(n-1)/2=45 pairs of nodes (indexed 0, 1, ..., 44). "from_pos" and "to_pos" refer to these 45 pairs of nodes. So, if you want to compute the relations for the pairs of nodes from 5 to 25 (from_pos=5, to_pos=25), there's a total of 20 pairs of nodes. "step_size" determines in how many iterations these 20 pairs of nodes are computed. If you set "step_size"=5, the relations of 5 pairs of nodes will be computed at each iteration, so 4 iterations are necessary to compute the relations of all 20 pairs of nodes from "from_pos" to "to_pos".
Hence "step_size" is not ignored, it determines how many pairs of nodes to process simultaneously at each iteration step, and is independent of "from_pos" and "to_pos".  
Does that make it more clear?
