### ISSUE TITLE
Append or join edge tables

### ISSUE THREAD

**Issue by rtbs-dev** [deepgraph/deepgraph#15]
Occasionally it is desirable to add edges to an edge table that e.g. was created from a graph partition. 
The user should be able to do this using the efficient `create_edges()` function, but this currently overwrites the `.e` table entirely, rather than performing a join on the currently-existing edge table. 

My example use case: 
- initial graph:
     - nodes are text spans from many documents, 
     - edges connecting the text when the spans are within the same sentence. 
- partition: on the span contents (the strings themselves)
     - nodes are unique strings found from the text
     - edges are weighted (n_edges) by their co-occurrence

This is all very nice to do with DeepGraph, using graph partitions (and is the setup for e.g. TextRank which is trivial using the `return_cs_graph()` function and some scipy). But say I want to add edges between tokens for possible misspellings? This would be done using `create_edges()` where the connector could be e.g. a `fuzzywuzzy.fuzz.ratio(string1, string2)`, or any other levenstein-based distance function. 

Currently, running such will delete the still-needed `n_edges` and any other nice edges/properties derived from the partition.

**Comment by dominiktraxl** [comment]
Hi there, sorry for the late reply.

Is there any argument against copying an existing edge table, and combining it with a newly created edge table yourself? Somehow along these lines, for instance:
```python
e_before = g.e.copy()
g.create_edges(..)
e_combined = pd.concat((e_before, g.e), axis=1, ..)
```
The reason I'm reluctant to implement this in the deepgraph package itself is that there are many ways you might want to combine the tables (merging, joining, concatenating, ..), with various kinds of set logic for the indexes and relational algebra functionality for join/merge-type operations. I think it's easiest to to just copy the existing edge table, create a new one, and then combine them according to your requirements. 

Or is there anything I've missed?
