### ISSUE TITLE
Please distribute as wheel

### ISSUE THREAD

**Issue by afrendeiro** [deepgraph/deepgraph#18]
It would greatly facilitate the install process if you could please distribute the package as `wheel` on PyPI (https://packaging.python.org/en/latest/flow/#the-built-distributions-wheels).

**Comment by dominiktraxl** [comment]
Hi @afrendeiro,
I just had a look into this, and it seems non-trivial and quite a lot of work to build wheels for all combinations of Python versions, operating systems, and CPU architectures. Do you have the option to install via conda? That would be the easiest way. 
If you have a suggestion on how to easily build wheels, let me know, and I'll give it another look.
